### ISSUE TITLE
"MOT 2020 Labels" and "MOT 2020 Images"

### ISSUE THREAD

**Issue by Harish-Agrawal** [bdd100k/bdd100k#220] opened 2022-04-10 05:27 UTC
### Discussed in https://github.com/bdd100k/bdd100k/discussions/204

<div type='discussions-op-text'>

<sup>Originally posted by **KalyanaVarma** January  5, 2022</sup>
Hi,
I am not able to download MOT 2020 Images. I have tried downloading them on chrome as well as firefox browsers but everytime I try the download starts and after downloading some 400 MB of data it stops. I have even tried downloading using terminal(wget) but facing the same issue.
Can you please let me know of any solution to this?

Thanks</div>

**Comment by thomasehuang** [comment] 2022-04-11 12:33
Duplicate of #221.

**Closed by thomasehuang** 2022-04-11 12:33 UTC
